/*
 * generated by Xtext 2.16.0
 */
package mgpl.serializer;

import com.google.inject.Inject;
import java.util.List;
import mgpl.services.MGPLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class MGPLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MGPLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_PrimExpr_LeftParenthesisKeyword_2_0_a;
	protected AbstractElementAlias match_PrimExpr_LeftParenthesisKeyword_2_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MGPLGrammarAccess) access;
		match_PrimExpr_LeftParenthesisKeyword_2_0_a = new TokenAlias(true, true, grammarAccess.getPrimExprAccess().getLeftParenthesisKeyword_2_0());
		match_PrimExpr_LeftParenthesisKeyword_2_0_p = new TokenAlias(true, false, grammarAccess.getPrimExprAccess().getLeftParenthesisKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_PrimExpr_LeftParenthesisKeyword_2_0_a.equals(syntax))
				emit_PrimExpr_LeftParenthesisKeyword_2_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PrimExpr_LeftParenthesisKeyword_2_0_p.equals(syntax))
				emit_PrimExpr_LeftParenthesisKeyword_2_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '=' (ambiguity) '!' expr=UnaryExpr
	 *     (rule start) '=' (ambiguity) '-' expr=UnaryExpr
	 *     (rule start) '=' (ambiguity) id=[AllDecls|IDF]
	 *     (rule start) '=' (ambiguity) value=NUMBER
	 *     (rule start) '=' (ambiguity) {And.left=}
	 *     (rule start) '=' (ambiguity) {Divide.left=}
	 *     (rule start) '=' (ambiguity) {ElementSelect.variable=}
	 *     (rule start) '=' (ambiguity) {Equals.left=}
	 *     (rule start) '=' (ambiguity) {Less.left=}
	 *     (rule start) '=' (ambiguity) {LessOrEquals.left=}
	 *     (rule start) '=' (ambiguity) {MemberSelect.variable=}
	 *     (rule start) '=' (ambiguity) {Minus.left=}
	 *     (rule start) '=' (ambiguity) {Or.left=}
	 *     (rule start) '=' (ambiguity) {Plus.left=}
	 *     (rule start) '=' (ambiguity) {Times.left=}
	 *     (rule start) '=' (ambiguity) {Touches.left=}
	 *     (rule start) (ambiguity) '!' expr=UnaryExpr
	 *     (rule start) (ambiguity) '-' expr=UnaryExpr
	 *     (rule start) (ambiguity) id=[AllDecls|IDF]
	 *     (rule start) (ambiguity) value=NUMBER
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {ElementSelect.variable=}
	 *     (rule start) (ambiguity) {Equals.left=}
	 *     (rule start) (ambiguity) {Less.left=}
	 *     (rule start) (ambiguity) {LessOrEquals.left=}
	 *     (rule start) (ambiguity) {MemberSelect.variable=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 *     (rule start) (ambiguity) {Times.left=}
	 *     (rule start) (ambiguity) {Touches.left=}
	 */
	protected void emit_PrimExpr_LeftParenthesisKeyword_2_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' expr=UnaryExpr
	 *     (rule start) (ambiguity) '-' expr=UnaryExpr
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Equals.left=}
	 *     (rule start) (ambiguity) {Less.left=}
	 *     (rule start) (ambiguity) {LessOrEquals.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 *     (rule start) (ambiguity) {Times.left=}
	 */
	protected void emit_PrimExpr_LeftParenthesisKeyword_2_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
