/*
 * generated by Xtext 2.16.0
 */
package mgpl.ide

import com.google.inject.Guice
import mgpl.MGPLRuntimeModule
import mgpl.MGPLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MGPLIdeSetup extends MGPLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MGPLRuntimeModule, new MGPLIdeModule))
	}
	
}
