/*
 * generated by Xtext 2.9.0
 */
package mgpl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MGPLRuntimeModule extends AbstractMGPLRuntimeModule {
}
