/*
 * generated by Xtext 2.9.0
 */
package mgpl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MGPLStandaloneSetup extends MGPLStandaloneSetupGenerated {

	def static void doSetup() {
		new MGPLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
