/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anim Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.AnimBlock#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getAnimBlock()
 * @model
 * @generated
 */
public interface AnimBlock extends Block, AllDecls
{
  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference.
   * @see #setParam(ParamDecl)
   * @see mgpl.mGPL.MGPLPackage#getAnimBlock_Param()
   * @model containment="true"
   * @generated
   */
  ParamDecl getParam();

  /**
   * Sets the value of the '{@link mgpl.mGPL.AnimBlock#getParam <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' containment reference.
   * @see #getParam()
   * @generated
   */
  void setParam(ParamDecl value);

} // AnimBlock
