/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.Block#getStmtBlock <em>Stmt Block</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getBlock()
 * @model
 * @generated
 */
public interface Block extends EObject
{
  /**
   * Returns the value of the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stmt Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt Block</em>' containment reference.
   * @see #setStmtBlock(StmtBlock)
   * @see mgpl.mGPL.MGPLPackage#getBlock_StmtBlock()
   * @model containment="true"
   * @generated
   */
  StmtBlock getStmtBlock();

  /**
   * Sets the value of the '{@link mgpl.mGPL.Block#getStmtBlock <em>Stmt Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt Block</em>' containment reference.
   * @see #getStmtBlock()
   * @generated
   */
  void setStmtBlock(StmtBlock value);

} // Block
