/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.IfStmt#getCondition <em>Condition</em>}</li>
 *   <li>{@link mgpl.mGPL.IfStmt#getThenBlock <em>Then Block</em>}</li>
 *   <li>{@link mgpl.mGPL.IfStmt#getElseBlock <em>Else Block</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getIfStmt()
 * @model
 * @generated
 */
public interface IfStmt extends Stmt
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expr)
   * @see mgpl.mGPL.MGPLPackage#getIfStmt_Condition()
   * @model containment="true"
   * @generated
   */
  Expr getCondition();

  /**
   * Sets the value of the '{@link mgpl.mGPL.IfStmt#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expr value);

  /**
   * Returns the value of the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Block</em>' containment reference.
   * @see #setThenBlock(StmtBlock)
   * @see mgpl.mGPL.MGPLPackage#getIfStmt_ThenBlock()
   * @model containment="true"
   * @generated
   */
  StmtBlock getThenBlock();

  /**
   * Sets the value of the '{@link mgpl.mGPL.IfStmt#getThenBlock <em>Then Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Block</em>' containment reference.
   * @see #getThenBlock()
   * @generated
   */
  void setThenBlock(StmtBlock value);

  /**
   * Returns the value of the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Block</em>' containment reference.
   * @see #setElseBlock(StmtBlock)
   * @see mgpl.mGPL.MGPLPackage#getIfStmt_ElseBlock()
   * @model containment="true"
   * @generated
   */
  StmtBlock getElseBlock();

  /**
   * Sets the value of the '{@link mgpl.mGPL.IfStmt#getElseBlock <em>Else Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Block</em>' containment reference.
   * @see #getElseBlock()
   * @generated
   */
  void setElseBlock(StmtBlock value);

} // IfStmt
