/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.MemberSelect#getMemberName <em>Member Name</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getMemberSelect()
 * @model
 * @generated
 */
public interface MemberSelect extends Var
{
  /**
   * Returns the value of the '<em><b>Member Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Member Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member Name</em>' attribute.
   * @see #setMemberName(String)
   * @see mgpl.mGPL.MGPLPackage#getMemberSelect_MemberName()
   * @model
   * @generated
   */
  String getMemberName();

  /**
   * Sets the value of the '{@link mgpl.mGPL.MemberSelect#getMemberName <em>Member Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member Name</em>' attribute.
   * @see #getMemberName()
   * @generated
   */
  void setMemberName(String value);

} // MemberSelect
