/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mgpl.mGPL.MGPLFactory
 * @model kind="package"
 * @generated
 */
public interface MGPLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mGPL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.MGPL.mgpl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mGPL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MGPLPackage eINSTANCE = mgpl.mGPL.impl.MGPLPackageImpl.init();

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.AllDeclsImpl <em>All Decls</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.AllDeclsImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getAllDecls()
   * @generated
   */
  int ALL_DECLS = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_DECLS__NAME = 0;

  /**
   * The number of structural features of the '<em>All Decls</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_DECLS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ProgImpl <em>Prog</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ProgImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getProg()
   * @generated
   */
  int PROG = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__NAME = ALL_DECLS__NAME;

  /**
   * The feature id for the '<em><b>Attr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__ATTR = ALL_DECLS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__DECLARATIONS = ALL_DECLS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__INIT = ALL_DECLS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__BLOCKS = ALL_DECLS_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Prog</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG_FEATURE_COUNT = ALL_DECLS_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.DeclImpl <em>Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.DeclImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getDecl()
   * @generated
   */
  int DECL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__NAME = ALL_DECLS__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__TYPE = ALL_DECLS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_FEATURE_COUNT = ALL_DECLS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.VarDeclImpl <em>Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.VarDeclImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getVarDecl()
   * @generated
   */
  int VAR_DECL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__TYPE = DECL__TYPE;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__INIT = DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.InitImpl <em>Init</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.InitImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getInit()
   * @generated
   */
  int INIT = 3;

  /**
   * The number of structural features of the '<em>Init</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ObjDeclImpl <em>Obj Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ObjDeclImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getObjDecl()
   * @generated
   */
  int OBJ_DECL = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__TYPE = DECL__TYPE;

  /**
   * The feature id for the '<em><b>Attr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__ATTR = DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Obj Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.AttrAssImpl <em>Attr Ass</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.AttrAssImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getAttrAss()
   * @generated
   */
  int ATTR_ASS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS__VALUE = 1;

  /**
   * The number of structural features of the '<em>Attr Ass</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.BlockImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 6;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__STMT_BLOCK = 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.AnimBlockImpl <em>Anim Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.AnimBlockImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getAnimBlock()
   * @generated
   */
  int ANIM_BLOCK = 7;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__STMT_BLOCK = BLOCK__STMT_BLOCK;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__NAME = BLOCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__PARAM = BLOCK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Anim Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ParamDeclImpl <em>Param Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ParamDeclImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getParamDecl()
   * @generated
   */
  int PARAM_DECL = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_DECL__NAME = ALL_DECLS__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_DECL__TYPE = ALL_DECLS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Param Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_DECL_FEATURE_COUNT = ALL_DECLS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.EventBlockImpl <em>Event Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.EventBlockImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getEventBlock()
   * @generated
   */
  int EVENT_BLOCK = 9;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK__STMT_BLOCK = BLOCK__STMT_BLOCK;

  /**
   * The feature id for the '<em><b>Key Stroke</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK__KEY_STROKE = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Event Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.StmtBlockImpl <em>Stmt Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.StmtBlockImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getStmtBlock()
   * @generated
   */
  int STMT_BLOCK = 10;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_BLOCK__STMTS = 0;

  /**
   * The number of structural features of the '<em>Stmt Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.StmtImpl <em>Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.StmtImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getStmt()
   * @generated
   */
  int STMT = 11;

  /**
   * The number of structural features of the '<em>Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.IfStmtImpl <em>If Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.IfStmtImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getIfStmt()
   * @generated
   */
  int IF_STMT = 12;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__CONDITION = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__THEN_BLOCK = STMT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__ELSE_BLOCK = STMT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ForStmtImpl <em>For Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ForStmtImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getForStmt()
   * @generated
   */
  int FOR_STMT = 13;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__INIT = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__CONDITION = STMT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Loop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__LOOP = STMT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__STMT_BLOCK = STMT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>For Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.AssStmtImpl <em>Ass Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.AssStmtImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getAssStmt()
   * @generated
   */
  int ASS_STMT = 14;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT__VARIABLE = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT__EXPRESSION = STMT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ass Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ExprImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 17;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = INIT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.VarImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getVar()
   * @generated
   */
  int VAR = 16;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__ID = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__VARIABLE = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ArrayDeclImpl <em>Array Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ArrayDeclImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getArrayDecl()
   * @generated
   */
  int ARRAY_DECL = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL__NAME = VAR_DECL__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL__TYPE = VAR_DECL__TYPE;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL__INIT = VAR_DECL__INIT;

  /**
   * The feature id for the '<em><b>Attr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL__ATTR = VAR_DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL__VARIABLE = VAR_DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL__LENGTH = VAR_DECL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Array Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_DECL_FEATURE_COUNT = VAR_DECL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ElementSelectImpl <em>Element Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ElementSelectImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getElementSelect()
   * @generated
   */
  int ELEMENT_SELECT = 19;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_SELECT__ID = VAR__ID;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_SELECT__VARIABLE = VAR__VARIABLE;

  /**
   * The feature id for the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_SELECT__INDEX = VAR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Element Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_SELECT_FEATURE_COUNT = VAR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.MemberSelectImpl <em>Member Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.MemberSelectImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getMemberSelect()
   * @generated
   */
  int MEMBER_SELECT = 20;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_SELECT__ID = VAR__ID;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_SELECT__VARIABLE = VAR__VARIABLE;

  /**
   * The feature id for the '<em><b>Member Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_SELECT__MEMBER_NAME = VAR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Member Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_SELECT_FEATURE_COUNT = VAR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.OrImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getOr()
   * @generated
   */
  int OR = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.AndImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getAnd()
   * @generated
   */
  int AND = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.EqualsImpl <em>Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.EqualsImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getEquals()
   * @generated
   */
  int EQUALS = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.LessImpl <em>Less</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.LessImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getLess()
   * @generated
   */
  int LESS = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Less</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.LessOrEqualsImpl <em>Less Or Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.LessOrEqualsImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getLessOrEquals()
   * @generated
   */
  int LESS_OR_EQUALS = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUALS__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUALS__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Less Or Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUALS_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.PlusImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getPlus()
   * @generated
   */
  int PLUS = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.MinusImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getMinus()
   * @generated
   */
  int MINUS = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.DivideImpl <em>Divide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.DivideImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getDivide()
   * @generated
   */
  int DIVIDE = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Divide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.TimesImpl <em>Times</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.TimesImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getTimes()
   * @generated
   */
  int TIMES = 29;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMES__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMES__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Times</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMES_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.NegationImpl <em>Negation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.NegationImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getNegation()
   * @generated
   */
  int NEGATION = 30;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION__EXPR = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Negation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.ComplementImpl <em>Complement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.ComplementImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getComplement()
   * @generated
   */
  int COMPLEMENT = 31;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT__EXPR = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Complement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEMENT_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.NumberLiteralImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 32;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mgpl.mGPL.impl.TouchesImpl <em>Touches</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mgpl.mGPL.impl.TouchesImpl
   * @see mgpl.mGPL.impl.MGPLPackageImpl#getTouches()
   * @generated
   */
  int TOUCHES = 33;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCHES__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCHES__RIGHT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Touches</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCHES_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Prog <em>Prog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prog</em>'.
   * @see mgpl.mGPL.Prog
   * @generated
   */
  EClass getProg();

  /**
   * Returns the meta object for the containment reference list '{@link mgpl.mGPL.Prog#getAttr <em>Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attr</em>'.
   * @see mgpl.mGPL.Prog#getAttr()
   * @see #getProg()
   * @generated
   */
  EReference getProg_Attr();

  /**
   * Returns the meta object for the containment reference list '{@link mgpl.mGPL.Prog#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see mgpl.mGPL.Prog#getDeclarations()
   * @see #getProg()
   * @generated
   */
  EReference getProg_Declarations();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Prog#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see mgpl.mGPL.Prog#getInit()
   * @see #getProg()
   * @generated
   */
  EReference getProg_Init();

  /**
   * Returns the meta object for the containment reference list '{@link mgpl.mGPL.Prog#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see mgpl.mGPL.Prog#getBlocks()
   * @see #getProg()
   * @generated
   */
  EReference getProg_Blocks();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Decl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl</em>'.
   * @see mgpl.mGPL.Decl
   * @generated
   */
  EClass getDecl();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.Decl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see mgpl.mGPL.Decl#getType()
   * @see #getDecl()
   * @generated
   */
  EAttribute getDecl_Type();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.VarDecl <em>Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Decl</em>'.
   * @see mgpl.mGPL.VarDecl
   * @generated
   */
  EClass getVarDecl();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.VarDecl#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see mgpl.mGPL.VarDecl#getInit()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_Init();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Init <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Init</em>'.
   * @see mgpl.mGPL.Init
   * @generated
   */
  EClass getInit();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.ObjDecl <em>Obj Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obj Decl</em>'.
   * @see mgpl.mGPL.ObjDecl
   * @generated
   */
  EClass getObjDecl();

  /**
   * Returns the meta object for the containment reference list '{@link mgpl.mGPL.ObjDecl#getAttr <em>Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attr</em>'.
   * @see mgpl.mGPL.ObjDecl#getAttr()
   * @see #getObjDecl()
   * @generated
   */
  EReference getObjDecl_Attr();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.AttrAss <em>Attr Ass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Ass</em>'.
   * @see mgpl.mGPL.AttrAss
   * @generated
   */
  EClass getAttrAss();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.AttrAss#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mgpl.mGPL.AttrAss#getName()
   * @see #getAttrAss()
   * @generated
   */
  EAttribute getAttrAss_Name();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.AttrAss#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see mgpl.mGPL.AttrAss#getValue()
   * @see #getAttrAss()
   * @generated
   */
  EReference getAttrAss_Value();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see mgpl.mGPL.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Block#getStmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt Block</em>'.
   * @see mgpl.mGPL.Block#getStmtBlock()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_StmtBlock();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.AnimBlock <em>Anim Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Anim Block</em>'.
   * @see mgpl.mGPL.AnimBlock
   * @generated
   */
  EClass getAnimBlock();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.AnimBlock#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param</em>'.
   * @see mgpl.mGPL.AnimBlock#getParam()
   * @see #getAnimBlock()
   * @generated
   */
  EReference getAnimBlock_Param();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.ParamDecl <em>Param Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Decl</em>'.
   * @see mgpl.mGPL.ParamDecl
   * @generated
   */
  EClass getParamDecl();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.ParamDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see mgpl.mGPL.ParamDecl#getType()
   * @see #getParamDecl()
   * @generated
   */
  EAttribute getParamDecl_Type();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.EventBlock <em>Event Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Block</em>'.
   * @see mgpl.mGPL.EventBlock
   * @generated
   */
  EClass getEventBlock();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.EventBlock#getKeyStroke <em>Key Stroke</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key Stroke</em>'.
   * @see mgpl.mGPL.EventBlock#getKeyStroke()
   * @see #getEventBlock()
   * @generated
   */
  EAttribute getEventBlock_KeyStroke();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.StmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stmt Block</em>'.
   * @see mgpl.mGPL.StmtBlock
   * @generated
   */
  EClass getStmtBlock();

  /**
   * Returns the meta object for the containment reference list '{@link mgpl.mGPL.StmtBlock#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see mgpl.mGPL.StmtBlock#getStmts()
   * @see #getStmtBlock()
   * @generated
   */
  EReference getStmtBlock_Stmts();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Stmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stmt</em>'.
   * @see mgpl.mGPL.Stmt
   * @generated
   */
  EClass getStmt();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.IfStmt <em>If Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Stmt</em>'.
   * @see mgpl.mGPL.IfStmt
   * @generated
   */
  EClass getIfStmt();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.IfStmt#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see mgpl.mGPL.IfStmt#getCondition()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Condition();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.IfStmt#getThenBlock <em>Then Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Block</em>'.
   * @see mgpl.mGPL.IfStmt#getThenBlock()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_ThenBlock();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.IfStmt#getElseBlock <em>Else Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Block</em>'.
   * @see mgpl.mGPL.IfStmt#getElseBlock()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_ElseBlock();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.ForStmt <em>For Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Stmt</em>'.
   * @see mgpl.mGPL.ForStmt
   * @generated
   */
  EClass getForStmt();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.ForStmt#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see mgpl.mGPL.ForStmt#getInit()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Init();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.ForStmt#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see mgpl.mGPL.ForStmt#getCondition()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Condition();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.ForStmt#getLoop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Loop</em>'.
   * @see mgpl.mGPL.ForStmt#getLoop()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_Loop();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.ForStmt#getStmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt Block</em>'.
   * @see mgpl.mGPL.ForStmt#getStmtBlock()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_StmtBlock();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.AssStmt <em>Ass Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ass Stmt</em>'.
   * @see mgpl.mGPL.AssStmt
   * @generated
   */
  EClass getAssStmt();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.AssStmt#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see mgpl.mGPL.AssStmt#getVariable()
   * @see #getAssStmt()
   * @generated
   */
  EReference getAssStmt_Variable();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.AssStmt#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see mgpl.mGPL.AssStmt#getExpression()
   * @see #getAssStmt()
   * @generated
   */
  EReference getAssStmt_Expression();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.AllDecls <em>All Decls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Decls</em>'.
   * @see mgpl.mGPL.AllDecls
   * @generated
   */
  EClass getAllDecls();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.AllDecls#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mgpl.mGPL.AllDecls#getName()
   * @see #getAllDecls()
   * @generated
   */
  EAttribute getAllDecls_Name();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see mgpl.mGPL.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the reference '{@link mgpl.mGPL.Var#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see mgpl.mGPL.Var#getId()
   * @see #getVar()
   * @generated
   */
  EReference getVar_Id();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Var#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see mgpl.mGPL.Var#getVariable()
   * @see #getVar()
   * @generated
   */
  EReference getVar_Variable();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see mgpl.mGPL.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.ArrayDecl <em>Array Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Decl</em>'.
   * @see mgpl.mGPL.ArrayDecl
   * @generated
   */
  EClass getArrayDecl();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.ArrayDecl#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see mgpl.mGPL.ArrayDecl#getVariable()
   * @see #getArrayDecl()
   * @generated
   */
  EReference getArrayDecl_Variable();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.ArrayDecl#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see mgpl.mGPL.ArrayDecl#getLength()
   * @see #getArrayDecl()
   * @generated
   */
  EAttribute getArrayDecl_Length();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.ElementSelect <em>Element Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element Select</em>'.
   * @see mgpl.mGPL.ElementSelect
   * @generated
   */
  EClass getElementSelect();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.ElementSelect#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Index</em>'.
   * @see mgpl.mGPL.ElementSelect#getIndex()
   * @see #getElementSelect()
   * @generated
   */
  EReference getElementSelect_Index();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.MemberSelect <em>Member Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member Select</em>'.
   * @see mgpl.mGPL.MemberSelect
   * @generated
   */
  EClass getMemberSelect();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.MemberSelect#getMemberName <em>Member Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Member Name</em>'.
   * @see mgpl.mGPL.MemberSelect#getMemberName()
   * @see #getMemberSelect()
   * @generated
   */
  EAttribute getMemberSelect_MemberName();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see mgpl.mGPL.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see mgpl.mGPL.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Equals <em>Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equals</em>'.
   * @see mgpl.mGPL.Equals
   * @generated
   */
  EClass getEquals();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Equals#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Equals#getLeft()
   * @see #getEquals()
   * @generated
   */
  EReference getEquals_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Equals#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Equals#getRight()
   * @see #getEquals()
   * @generated
   */
  EReference getEquals_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Less <em>Less</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less</em>'.
   * @see mgpl.mGPL.Less
   * @generated
   */
  EClass getLess();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Less#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Less#getLeft()
   * @see #getLess()
   * @generated
   */
  EReference getLess_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Less#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Less#getRight()
   * @see #getLess()
   * @generated
   */
  EReference getLess_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.LessOrEquals <em>Less Or Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less Or Equals</em>'.
   * @see mgpl.mGPL.LessOrEquals
   * @generated
   */
  EClass getLessOrEquals();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.LessOrEquals#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.LessOrEquals#getLeft()
   * @see #getLessOrEquals()
   * @generated
   */
  EReference getLessOrEquals_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.LessOrEquals#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.LessOrEquals#getRight()
   * @see #getLessOrEquals()
   * @generated
   */
  EReference getLessOrEquals_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see mgpl.mGPL.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see mgpl.mGPL.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Divide <em>Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divide</em>'.
   * @see mgpl.mGPL.Divide
   * @generated
   */
  EClass getDivide();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Divide#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Divide#getLeft()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Divide#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Divide#getRight()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Times <em>Times</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Times</em>'.
   * @see mgpl.mGPL.Times
   * @generated
   */
  EClass getTimes();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Times#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Times#getLeft()
   * @see #getTimes()
   * @generated
   */
  EReference getTimes_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Times#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Times#getRight()
   * @see #getTimes()
   * @generated
   */
  EReference getTimes_Right();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Negation <em>Negation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negation</em>'.
   * @see mgpl.mGPL.Negation
   * @generated
   */
  EClass getNegation();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Negation#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see mgpl.mGPL.Negation#getExpr()
   * @see #getNegation()
   * @generated
   */
  EReference getNegation_Expr();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Complement <em>Complement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complement</em>'.
   * @see mgpl.mGPL.Complement
   * @generated
   */
  EClass getComplement();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Complement#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see mgpl.mGPL.Complement#getExpr()
   * @see #getComplement()
   * @generated
   */
  EReference getComplement_Expr();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see mgpl.mGPL.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link mgpl.mGPL.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see mgpl.mGPL.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link mgpl.mGPL.Touches <em>Touches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Touches</em>'.
   * @see mgpl.mGPL.Touches
   * @generated
   */
  EClass getTouches();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Touches#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mgpl.mGPL.Touches#getLeft()
   * @see #getTouches()
   * @generated
   */
  EReference getTouches_Left();

  /**
   * Returns the meta object for the containment reference '{@link mgpl.mGPL.Touches#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see mgpl.mGPL.Touches#getRight()
   * @see #getTouches()
   * @generated
   */
  EReference getTouches_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MGPLFactory getMGPLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ProgImpl <em>Prog</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ProgImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getProg()
     * @generated
     */
    EClass PROG = eINSTANCE.getProg();

    /**
     * The meta object literal for the '<em><b>Attr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROG__ATTR = eINSTANCE.getProg_Attr();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROG__DECLARATIONS = eINSTANCE.getProg_Declarations();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROG__INIT = eINSTANCE.getProg_Init();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROG__BLOCKS = eINSTANCE.getProg_Blocks();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.DeclImpl <em>Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.DeclImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getDecl()
     * @generated
     */
    EClass DECL = eINSTANCE.getDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECL__TYPE = eINSTANCE.getDecl_Type();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.VarDeclImpl <em>Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.VarDeclImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getVarDecl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getVarDecl();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__INIT = eINSTANCE.getVarDecl_Init();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.InitImpl <em>Init</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.InitImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getInit()
     * @generated
     */
    EClass INIT = eINSTANCE.getInit();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ObjDeclImpl <em>Obj Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ObjDeclImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getObjDecl()
     * @generated
     */
    EClass OBJ_DECL = eINSTANCE.getObjDecl();

    /**
     * The meta object literal for the '<em><b>Attr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJ_DECL__ATTR = eINSTANCE.getObjDecl_Attr();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.AttrAssImpl <em>Attr Ass</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.AttrAssImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getAttrAss()
     * @generated
     */
    EClass ATTR_ASS = eINSTANCE.getAttrAss();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_ASS__NAME = eINSTANCE.getAttrAss_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTR_ASS__VALUE = eINSTANCE.getAttrAss_Value();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.BlockImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Stmt Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__STMT_BLOCK = eINSTANCE.getBlock_StmtBlock();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.AnimBlockImpl <em>Anim Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.AnimBlockImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getAnimBlock()
     * @generated
     */
    EClass ANIM_BLOCK = eINSTANCE.getAnimBlock();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANIM_BLOCK__PARAM = eINSTANCE.getAnimBlock_Param();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ParamDeclImpl <em>Param Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ParamDeclImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getParamDecl()
     * @generated
     */
    EClass PARAM_DECL = eINSTANCE.getParamDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_DECL__TYPE = eINSTANCE.getParamDecl_Type();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.EventBlockImpl <em>Event Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.EventBlockImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getEventBlock()
     * @generated
     */
    EClass EVENT_BLOCK = eINSTANCE.getEventBlock();

    /**
     * The meta object literal for the '<em><b>Key Stroke</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_BLOCK__KEY_STROKE = eINSTANCE.getEventBlock_KeyStroke();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.StmtBlockImpl <em>Stmt Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.StmtBlockImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getStmtBlock()
     * @generated
     */
    EClass STMT_BLOCK = eINSTANCE.getStmtBlock();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STMT_BLOCK__STMTS = eINSTANCE.getStmtBlock_Stmts();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.StmtImpl <em>Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.StmtImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getStmt()
     * @generated
     */
    EClass STMT = eINSTANCE.getStmt();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.IfStmtImpl <em>If Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.IfStmtImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getIfStmt()
     * @generated
     */
    EClass IF_STMT = eINSTANCE.getIfStmt();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__CONDITION = eINSTANCE.getIfStmt_Condition();

    /**
     * The meta object literal for the '<em><b>Then Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__THEN_BLOCK = eINSTANCE.getIfStmt_ThenBlock();

    /**
     * The meta object literal for the '<em><b>Else Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__ELSE_BLOCK = eINSTANCE.getIfStmt_ElseBlock();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ForStmtImpl <em>For Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ForStmtImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getForStmt()
     * @generated
     */
    EClass FOR_STMT = eINSTANCE.getForStmt();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__INIT = eINSTANCE.getForStmt_Init();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__CONDITION = eINSTANCE.getForStmt_Condition();

    /**
     * The meta object literal for the '<em><b>Loop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__LOOP = eINSTANCE.getForStmt_Loop();

    /**
     * The meta object literal for the '<em><b>Stmt Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__STMT_BLOCK = eINSTANCE.getForStmt_StmtBlock();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.AssStmtImpl <em>Ass Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.AssStmtImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getAssStmt()
     * @generated
     */
    EClass ASS_STMT = eINSTANCE.getAssStmt();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASS_STMT__VARIABLE = eINSTANCE.getAssStmt_Variable();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASS_STMT__EXPRESSION = eINSTANCE.getAssStmt_Expression();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.AllDeclsImpl <em>All Decls</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.AllDeclsImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getAllDecls()
     * @generated
     */
    EClass ALL_DECLS = eINSTANCE.getAllDecls();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALL_DECLS__NAME = eINSTANCE.getAllDecls_Name();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.VarImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR__ID = eINSTANCE.getVar_Id();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR__VARIABLE = eINSTANCE.getVar_Variable();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ExprImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ArrayDeclImpl <em>Array Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ArrayDeclImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getArrayDecl()
     * @generated
     */
    EClass ARRAY_DECL = eINSTANCE.getArrayDecl();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_DECL__VARIABLE = eINSTANCE.getArrayDecl_Variable();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_DECL__LENGTH = eINSTANCE.getArrayDecl_Length();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ElementSelectImpl <em>Element Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ElementSelectImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getElementSelect()
     * @generated
     */
    EClass ELEMENT_SELECT = eINSTANCE.getElementSelect();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT_SELECT__INDEX = eINSTANCE.getElementSelect_Index();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.MemberSelectImpl <em>Member Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.MemberSelectImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getMemberSelect()
     * @generated
     */
    EClass MEMBER_SELECT = eINSTANCE.getMemberSelect();

    /**
     * The meta object literal for the '<em><b>Member Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMBER_SELECT__MEMBER_NAME = eINSTANCE.getMemberSelect_MemberName();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.OrImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.AndImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.EqualsImpl <em>Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.EqualsImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getEquals()
     * @generated
     */
    EClass EQUALS = eINSTANCE.getEquals();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALS__LEFT = eINSTANCE.getEquals_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALS__RIGHT = eINSTANCE.getEquals_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.LessImpl <em>Less</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.LessImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getLess()
     * @generated
     */
    EClass LESS = eINSTANCE.getLess();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS__LEFT = eINSTANCE.getLess_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS__RIGHT = eINSTANCE.getLess_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.LessOrEqualsImpl <em>Less Or Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.LessOrEqualsImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getLessOrEquals()
     * @generated
     */
    EClass LESS_OR_EQUALS = eINSTANCE.getLessOrEquals();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS_OR_EQUALS__LEFT = eINSTANCE.getLessOrEquals_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS_OR_EQUALS__RIGHT = eINSTANCE.getLessOrEquals_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.PlusImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.MinusImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.DivideImpl <em>Divide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.DivideImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getDivide()
     * @generated
     */
    EClass DIVIDE = eINSTANCE.getDivide();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__LEFT = eINSTANCE.getDivide_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__RIGHT = eINSTANCE.getDivide_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.TimesImpl <em>Times</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.TimesImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getTimes()
     * @generated
     */
    EClass TIMES = eINSTANCE.getTimes();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIMES__LEFT = eINSTANCE.getTimes_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIMES__RIGHT = eINSTANCE.getTimes_Right();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.NegationImpl <em>Negation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.NegationImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getNegation()
     * @generated
     */
    EClass NEGATION = eINSTANCE.getNegation();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEGATION__EXPR = eINSTANCE.getNegation_Expr();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.ComplementImpl <em>Complement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.ComplementImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getComplement()
     * @generated
     */
    EClass COMPLEMENT = eINSTANCE.getComplement();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEMENT__EXPR = eINSTANCE.getComplement_Expr();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.NumberLiteralImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link mgpl.mGPL.impl.TouchesImpl <em>Touches</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mgpl.mGPL.impl.TouchesImpl
     * @see mgpl.mGPL.impl.MGPLPackageImpl#getTouches()
     * @generated
     */
    EClass TOUCHES = eINSTANCE.getTouches();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOUCHES__LEFT = eINSTANCE.getTouches_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOUCHES__RIGHT = eINSTANCE.getTouches_Right();

  }

} //MGPLPackage
