/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obj Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.ObjDecl#getAttr <em>Attr</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getObjDecl()
 * @model
 * @generated
 */
public interface ObjDecl extends Decl
{
  /**
   * Returns the value of the '<em><b>Attr</b></em>' containment reference list.
   * The list contents are of type {@link mgpl.mGPL.AttrAss}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attr</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr</em>' containment reference list.
   * @see mgpl.mGPL.MGPLPackage#getObjDecl_Attr()
   * @model containment="true"
   * @generated
   */
  EList<AttrAss> getAttr();

} // ObjDecl
