/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mgpl.mGPL.MGPLPackage#getStmt()
 * @model
 * @generated
 */
public interface Stmt extends EObject
{
} // Stmt
