/**
 * generated by Xtext 2.16.0
 */
package mgpl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mgpl.mGPL.Var#getId <em>Id</em>}</li>
 *   <li>{@link mgpl.mGPL.Var#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see mgpl.mGPL.MGPLPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends Expr
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(AllDecls)
   * @see mgpl.mGPL.MGPLPackage#getVar_Id()
   * @model
   * @generated
   */
  AllDecls getId();

  /**
   * Sets the value of the '{@link mgpl.mGPL.Var#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(AllDecls value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Var)
   * @see mgpl.mGPL.MGPLPackage#getVar_Variable()
   * @model containment="true"
   * @generated
   */
  Var getVariable();

  /**
   * Sets the value of the '{@link mgpl.mGPL.Var#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Var value);

} // Var
