/*
 * generated by Xtext 2.16.0
 */
package mgpl.parser.antlr;

import com.google.inject.Inject;
import mgpl.parser.antlr.internal.InternalMGPLParser;
import mgpl.services.MGPLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MGPLParser extends AbstractAntlrParser {

	@Inject
	private MGPLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_COMMENT");
	}
	

	@Override
	protected InternalMGPLParser createParser(XtextTokenStream stream) {
		return new InternalMGPLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Prog";
	}

	public MGPLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MGPLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
